######################################################################
# Automatically generated by qmake (3.0) ?? ??? 23 14:16:32 2020
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .
QT += widgets
LIBS += -lws2_32

# Input
SOURCES += main.cpp \
    clientwindow.cpp

HEADERS += \
    spx_func.h \
    clientwindow.h
