######################################################################
# Automatically generated by qmake (3.0) ?? ??? 23 14:16:32 2020
######################################################################

TEMPLATE = app
TARGET = server
INCLUDEPATH += .
QT += widgets
LIBS += -lws2_32

# Input
SOURCES += main.cpp \
    serverwindow.cpp

HEADERS += \
    spx_func.h \
    serverwindow.h
