#include <stdio.h>
#include "inputdataGen.h"
#include <time.h>
#include "sort.h"
int main(){
  float M=CLOCKS_PER_SEC;
  float tS,tE;
  int size;
  int *t;
  printf("\n\n\nRANDOM ARRAY\n\n\n");
  for (size=10000;size<50000;size+=5000){
  t=random_arrGen(size);
  tS=clock();
  InsSort(t,size);
  tE=clock();
  printf("Insert sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=random_arrGen(size);
  tS=clock();
  ShellSort(t,size);
  tE=clock();
  printf("Shell sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=random_arrGen(size);
  tS=clock();
  BSort(t,size);
  tE=clock();
  printf("Bubble sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=random_arrGen(size);
  tS=clock();
  SelSort(t,size);
  tE=clock();
  printf("Select sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=random_arrGen(size);
  tS=clock();
  HoarSort(t,size);
  tE=clock();
  printf("Hoar sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=random_arrGen(size);
  tS=clock();
  HeapSort(t,size);
  tE=clock();
  printf("Heap sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=random_arrGen(size);
  tS=clock();
  ba1Sort(t,size);
  tE=clock();
  printf("Swap sort 1 of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=random_arrGen(size);
  tS=clock();
  ba2Sort(t,size);
  tE=clock();
  printf("Swap sort 2 of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  printf("\n");
}
printf("\n\n\nSORTED ARRAY\n\n\n");
for (size=10000;size<50000;size+=5000){
  t=sorted_arrGen(size);
  tS=clock();
  InsSort(t,size);
  tE=clock();
  printf("Insert sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_arrGen(size);
  tS=clock();
  ShellSort(t,size);
  tE=clock();
  printf("Shell sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_arrGen(size);
  tS=clock();
  BSort(t,size);
  tE=clock();
  printf("Bubble sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_arrGen(size);
  tS=clock();
  SelSort(t,size);
  tE=clock();
  printf("Select sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_arrGen(size);
  tS=clock();
  HoarSort(t,size);
  tE=clock();
  printf("Hoar sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_arrGen(size);
  tS=clock();
  HeapSort(t,size);
  tE=clock();
  printf("Heap sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_arrGen(size);
  tS=clock();
  ba1Sort(t,size);
  tE=clock();
  printf("Swap sort 1 of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_arrGen(size);
  tS=clock();
  ba2Sort(t,size);
  tE=clock();
  printf("Swap sort 2 of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  printf("\n");
}
printf("\n\n\nREVERS SORTED ARRAY\n\n\n");
for (size=10000;size<50000;size+=5000){
  t=sorted_RarrGen(size);
  tS=clock();
  InsSort(t,size);
  tE=clock();
  printf("Insert sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_RarrGen(size);
  tS=clock();
  ShellSort(t,size);
  tE=clock();
  printf("Shell sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_RarrGen(size);
  tS=clock();
  BSort(t,size);
  tE=clock();
  printf("Bubble sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_RarrGen(size);
  tS=clock();
  SelSort(t,size);
  tE=clock();
  printf("Select sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_RarrGen(size);
  tS=clock();
  HoarSort(t,size);
  tE=clock();
  printf("Hoar sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_RarrGen(size);
  tS=clock();
  HeapSort(t,size);
  tE=clock();
  printf("Heap sort of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_RarrGen(size);
  tS=clock();
  ba1Sort(t,size);
  tE=clock();
  printf("Swap sort 1 of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  t=sorted_RarrGen(size);
  tS=clock();
  ba2Sort(t,size);
  tE=clock();
  printf("Swap sort 2 of %d elements complite on %f sec.\n",size,(tE-tS)/M);
  printf("\n");
}
  return 0;
}
